server:
  port: 3039
  servlet:
    context-path: /api
    session:
      cookie:
        # cookie 30 天后过期
        max-age: 2592000
spring:
  application:
    name: cqoj-backend
  profiles:
    # 选择配置文件
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 天过期
  session:
    store-type: redis
    timeout: 2592000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名
      logic-delete-field: isDelete
      # 逻辑已删除值（默认为 1）
      logic-delete-value: 1
      # 逻辑未删除值（默认为 0）
      logic-not-delete-value: 0
      id-type: assign_id
    banner: off
